[files]
extend-exclude = ["**/target/**", "**/serde-yaml/tests/**", "tests/evm_tester/indexes"]
ignore-files = true


[default.extend-words]
datas = "datas"
Storeable = "Storeable"
lits = "lits"
wich = "wich"
tre = "tre"
Hom = "Hom"

